### ISSUE TITLE
fix place markers

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-dark.tm2#1]
@andreasviglakis these should be resolution independent SVG icons, they look bad, especially on retina:

![screen shot 2015-01-22 at 1 38 29 pm](https://cloud.githubusercontent.com/assets/108094/5861967/fd4e8614-a23b-11e4-98f4-f9ff325d49ae.png)

**Comment by andreasviglakis** [comment]
![image](https://cloud.githubusercontent.com/assets/7102075/5863442/79358628-a22e-11e4-85c4-6a9036609a1a.png)

sorry about this, changes are pushed @samanpwbb
